/*
* generated by Xtext
*/
package ro.meetup.cpp.dsl.ui.contentassist;

import ro.meetup.cpp.dsl.ui.contentassist.AbstractDbDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DbDslProposalProvider extends AbstractDbDslProposalProvider {

}
