/*
* generated by Xtext
*/
package ro.meetup.cpp.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DbDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("ro/meetup/cpp/dsl/parser/antlr/internal/InternalDbDsl.tokens");
	}
}
