/*
* generated by Xtext
*/
package ro.meetup.cpp.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ro.meetup.cpp.dsl.services.DbDslGrammarAccess;

public class DbDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DbDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected ro.meetup.cpp.dsl.parser.antlr.internal.InternalDbDslParser createParser(XtextTokenStream stream) {
		return new ro.meetup.cpp.dsl.parser.antlr.internal.InternalDbDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public DbDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DbDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
