/*
 * generated by Xtext
 */
package ro.meetup.cpp.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DbDslRuntimeModule extends ro.meetup.cpp.dsl.AbstractDbDslRuntimeModule {

}
