#!/bin/bash-- # only source this file

# JustBuild:
#     It directly sets and uses PATH as instructed in its configuration files.
#
# Abcd with Jake or Make:
#     Jake and Make use the PATH generated by Abcd from its configuration files.
#
# Abcd with Ninja or Cmake:
#     The PATH variable have to be set from outside.
# * Use, for example, in bash:
#   `. path-for-ninja-cmake.sh`
#   or
#   `source path-for-ninja-cmake.sh`
# * Then run Ninja or CMake.
#

export PATH="$PATH:$PWD/abcd_main_conf/bin-hooks"
