/*
 * generated by Xtext
 */
package ro.meetup.cpp.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ro.meetup.cpp.dsl.ui.internal.DbDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DbDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DbDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DbDslActivator.getInstance().getInjector(DbDslActivator.RO_MEETUP_CPP_DSL_DBDSL);
	}
	
}
