/*
 * generated by Xtext
 */
package ro.meetup.cpp.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DbDslUiModule extends ro.meetup.cpp.dsl.ui.AbstractDbDslUiModule {
	public DbDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
